version: '3'

services:
  detran:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "detran"
    ports:
      - "15432:5432"    
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "allanbernardes85@gmail.com.br"
      PGADMIN_DEFAULT_PASSWORD: "teste123456"
    ports:
      - "16543:80"
    depends_on:
      - detran
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge